package tubes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 * 
 * @author Muhammad Refa Hermawan
 */
public class cashflow extends javax.swing.JFrame {
     /**
     * Creates new form cashflow
     */
   
    DefaultTableModel modelpemasukan;
    DefaultTableModel modelpengeluaran;
    public cashflow() {
        initComponents();
        
        String [] judulpemasukan={"Jumlah", "Keterangan"};
        modelpemasukan = new DefaultTableModel(judulpemasukan,0);
        tabelpemasukan.setModel(modelpemasukan);
        tampilkanpemasukan();
        
        String [] judulpengeluaran={"Jumlah", "Keterangan"};
        modelpengeluaran = new DefaultTableModel(judulpengeluaran,0);
        tabelpengeluaran.setModel(modelpengeluaran);
        tampilkanpengeluaran();
    }
    
    private void jumkan(){
         int total = 0;
            for (int a =0; a< tabelpemasukan.getRowCount(); a++){
            int amount = Integer.parseInt((String)tabelpemasukan.getValueAt(a, 0));
            total += amount;
                }
            totpem.setText(""+total);
        }
    private void jumran(){
            int total = 0;
            for (int b =0; b< tabelpengeluaran.getRowCount(); b++){
            int amount = Integer.parseInt((String)tabelpengeluaran.getValueAt(b, 0));
            total += amount;
                }
            totpeng.setText(""+total);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        tittle1 = new javax.swing.JLabel();
        sisauang = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        ok1 = new javax.swing.JButton();
        jumlah1 = new javax.swing.JLabel();
        pemasukan1 = new javax.swing.JLabel();
        txt_jml1 = new javax.swing.JTextField();
        txt_ket1 = new javax.swing.JTextField();
        keterangan1 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jml2 = new javax.swing.JTextField();
        pengeluaran1 = new javax.swing.JLabel();
        ok2 = new javax.swing.JButton();
        jumlah2 = new javax.swing.JLabel();
        keterangan2 = new javax.swing.JLabel();
        kt2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelpemasukan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelpengeluaran = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pemasukan2 = new javax.swing.JPanel();
        totpem = new javax.swing.JLabel();
        pengeluaran2 = new javax.swing.JPanel();
        totpeng = new javax.swing.JLabel();
        pemasukan3 = new javax.swing.JPanel();
        sisa = new javax.swing.JLabel();
        diagram = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Management Cash Flow");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(204, 204, 204));
        panel1.setBorder(new javax.swing.border.MatteBorder(null));

        tittle1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tittle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittle1.setText("Cash Flow Management ");
        tittle1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(tittle1)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tittle1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 6, 520, -1));

        sisauang.setBackground(new java.awt.Color(255, 51, 51));
        sisauang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sisauang.setText("HITUNG");
        sisauang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sisauang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisauangActionPerformed(evt);
            }
        });
        getContentPane().add(sisauang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 90, -1));

        panel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel2.setPreferredSize(new java.awt.Dimension(275, 130));

        ok1.setBackground(new java.awt.Color(0, 204, 51));
        ok1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ok1.setText("OK");
        ok1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });

        jumlah1.setText("Jumlah ");

        pemasukan1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pemasukan1.setText("Pemasukan");

        txt_ket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ket1ActionPerformed(evt);
            }
        });

        keterangan1.setText("Keterangan ");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(jumlah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pemasukan1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_jml1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(keterangan1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ket1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addComponent(pemasukan1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah1)
                    .addComponent(txt_jml1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keterangan1)
                    .addComponent(txt_ket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ok1)
                .addContainerGap())
        );

        panel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel3.setPreferredSize(new java.awt.Dimension(275, 121));

        pengeluaran1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pengeluaran1.setText("Pengeluaran ");

        ok2.setBackground(new java.awt.Color(0, 204, 51));
        ok2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ok2.setText("OK");
        ok2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok2ActionPerformed(evt);
            }
        });

        jumlah2.setText("Jumlah ");

        keterangan2.setText("Keterangan");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(keterangan2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ok2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kt2)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pengeluaran1)
                            .addComponent(jml2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addComponent(pengeluaran1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah2)
                    .addComponent(jml2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keterangan2)
                    .addComponent(kt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 57, 520, -1));

        tabelpemasukan.setBackground(new java.awt.Color(204, 204, 204));
        tabelpemasukan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelpemasukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Jumlah", "Keterangan", "Hari", "Tanggal"
            }
        ));
        tabelpemasukan.setToolTipText("");
        tabelpemasukan.setPreferredSize(new java.awt.Dimension(217, 121));
        tabelpemasukan.setShowGrid(true);
        jScrollPane3.setViewportView(tabelpemasukan);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 490, 110));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Pemasukan"));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 510, 140));

        tabelpengeluaran.setBackground(new java.awt.Color(204, 204, 204));
        tabelpengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Jumlah", "Keterangan", "Hari", "Tanggal"
            }
        ));
        tabelpengeluaran.setToolTipText("");
        tabelpengeluaran.setPreferredSize(new java.awt.Dimension(217, 121));
        tabelpengeluaran.setShowGrid(true);
        jScrollPane4.setViewportView(tabelpengeluaran);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 490, 110));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Pengeluaran"));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 510, 140));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        pemasukan2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pemasukan bulan Ini"));
        pemasukan2.setPreferredSize(new java.awt.Dimension(234, 23));

        totpem.setText("0");

        javax.swing.GroupLayout pemasukan2Layout = new javax.swing.GroupLayout(pemasukan2);
        pemasukan2.setLayout(pemasukan2Layout);
        pemasukan2Layout.setHorizontalGroup(
            pemasukan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemasukan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totpem, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
        pemasukan2Layout.setVerticalGroup(
            pemasukan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemasukan2Layout.createSequentialGroup()
                .addComponent(totpem, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(pemasukan2);

        pengeluaran2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pengeluaran bulan Ini"));
        pengeluaran2.setPreferredSize(new java.awt.Dimension(236, 23));

        totpeng.setText("0");

        javax.swing.GroupLayout pengeluaran2Layout = new javax.swing.GroupLayout(pengeluaran2);
        pengeluaran2.setLayout(pengeluaran2Layout);
        pengeluaran2Layout.setHorizontalGroup(
            pengeluaran2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengeluaran2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totpeng, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
        pengeluaran2Layout.setVerticalGroup(
            pengeluaran2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengeluaran2Layout.createSequentialGroup()
                .addComponent(totpeng, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(pengeluaran2);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 530, 60));

        pemasukan3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sisa uang"));
        pemasukan3.setPreferredSize(new java.awt.Dimension(234, 23));

        sisa.setText("0");

        javax.swing.GroupLayout pemasukan3Layout = new javax.swing.GroupLayout(pemasukan3);
        pemasukan3.setLayout(pemasukan3Layout);
        pemasukan3Layout.setHorizontalGroup(
            pemasukan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemasukan3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sisa, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
        pemasukan3Layout.setVerticalGroup(
            pemasukan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemasukan3Layout.createSequentialGroup()
                .addComponent(sisa, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pemasukan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 265, 60));

        diagram.setBackground(new java.awt.Color(0, 255, 51));
        diagram.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        diagram.setText("Tampilkan Diagram");
        diagram.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        diagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagramActionPerformed(evt);
            }
        });
        getContentPane().add(diagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
       try {
           // TODO add your handling code here:
           Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/manajemen_keuangan", "root", "");
           cn.createStatement().executeUpdate("Insert into data_pemasukan values "+" ( '"+txt_jml1.getText()+"','"+txt_ket1.getText()+"')" );
           tampilkanpemasukan();
       } catch (SQLException ex) {
             Logger.getLogger(cashflow.class.getName()).log(Level.SEVERE, null, ex); 
       }
        jumkan();
    }//GEN-LAST:event_ok1ActionPerformed

    private void ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok2ActionPerformed
        // TODO add your handling code here:
        try {
           // TODO add your handling code here:
           Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/manajemen_keuangan", "root", "");
           cn.createStatement().executeUpdate("Insert into data_pengeluaran values "+" ('"+jml2.getText()+"', '"+kt2.getText()+"')" );
           tampilkanpengeluaran();
       }  catch (SQLException ex){
           Logger.getLogger(cashflow.class.getName()).log(Level.SEVERE, null, ex); 
       }
        jumran();
    }//GEN-LAST:event_ok2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void txt_ket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ket1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ket1ActionPerformed

    private void sisauangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisauangActionPerformed
        int bil1;
        int bil2;
        int hasil1;
        bil1 = Integer.parseInt(totpem.getText());
        bil2 = Integer.parseInt(totpeng.getText());
        hasil1 = bil1 - bil2;
        sisa.setText(Integer.toString(hasil1));        // TODO add your handling code here:
    }//GEN-LAST:event_sisauangActionPerformed

    private void diagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagramActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset piedata=new DefaultCategoryDataset();
        piedata.setValue(Integer.parseInt(totpem.getText()),"warna", "Pemasukan");
        piedata.setValue(Integer.parseInt(totpeng.getText()),"warna", "Pengeluaran");
        
        
        JFreeChart chart = ChartFactory.createLineChart("Sisa Uang",null,null,piedata);
        ChartFrame frame =new ChartFrame ("Diagram",chart);
        frame.setVisible(true);
        frame.setBounds(500, 200, 500, 500);
    }//GEN-LAST:event_diagramActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashflow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton diagram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jml2;
    private javax.swing.JLabel jumlah1;
    private javax.swing.JLabel jumlah2;
    private javax.swing.JLabel keterangan1;
    private javax.swing.JLabel keterangan2;
    private javax.swing.JTextField kt2;
    private javax.swing.JButton ok1;
    private javax.swing.JButton ok2;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JLabel pemasukan1;
    private javax.swing.JPanel pemasukan2;
    private javax.swing.JPanel pemasukan3;
    private javax.swing.JLabel pengeluaran1;
    private javax.swing.JPanel pengeluaran2;
    private javax.swing.JLabel sisa;
    private javax.swing.JButton sisauang;
    private javax.swing.JTable tabelpemasukan;
    private javax.swing.JTable tabelpengeluaran;
    private javax.swing.JLabel tittle1;
    private javax.swing.JLabel totpem;
    private javax.swing.JLabel totpeng;
    private javax.swing.JTextField txt_jml1;
    private javax.swing.JTextField txt_ket1;
    // End of variables declaration//GEN-END:variables
    
    
    
    private void tampilkanpemasukan(){
          
                int row = tabelpemasukan.getRowCount();
                                for (int a=0; a<row; a++){
                    modelpemasukan.removeRow(0);
                }
                try{
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/manajemen_keuangan", "root", "");
                ResultSet rs = cn.createStatement().executeQuery("Select * FROM data_pemasukan");
                while(rs.next()){
                    String data1[]={rs.getString(1), rs.getString(2)};
                    modelpemasukan.addRow(data1);
                }
            } catch (SQLException ex) {
                Logger.getLogger(cashflow.class.getName()).log(Level.SEVERE, null, ex);
            }
           
    }
    
        private void tampilkanpengeluaran(){
                int row = tabelpengeluaran.getRowCount();
                for (int a=0; a<row; a++){
                    modelpengeluaran.removeRow(0);
                }
                try{
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/manajemen_keuangan", "root", "");
                ResultSet rs = cn.createStatement().executeQuery("Select * FROM data_pengeluaran");
                while(rs.next()){
                    String data2[]={rs.getString(1), rs.getString(2)};
                    modelpengeluaran.addRow(data2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(cashflow.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
   }


        
 
    

